build:
	gcc -std=c99 settings_panel.c -o ../side-panel-settings `pkg-config --libs --cflags glib-2.0 gmodule-2.0 gtk+-3.0`
	gcc -std=c99 settings_wallpaper.c -o ../side-wallpaper-settings `pkg-config --libs --cflags glib-2.0 gmodule-2.0 gtk+-3.0`
